### ISSUE TITLE
Add `@aws-sdk/client-s3` to allow image and video upload

### ISSUE THREAD

**Issue by haseakito** [haseakito/funbase#28]
### Issue

- Allow users to upload thumnail of posts and video in the posts

### Requirements

- Make new Bucket using [Terraform](https://www.terraform.io/)
- Add regin, access key and secrets to `.env` file 
- npm install the [AWS SDK for S3](https://docs.aws.amazon.com/AWSJavaScriptSDK/v3/latest/client/s3/)
- Follow the [guide](https://docs.aws.amazon.com/ja_jp/sdk-for-javascript/v2/developer-guide/s3-browser-examples.html)

### References

- [How to upload images in Amazon S3 bucket using NextJS Framework](https://medium.com/@louis_10840/how-to-interact-upload-files-get-files-with-amazon-s3-using-nextjs-app-fcbad408033b)
- [How to Upload Images and Videos to Amazon S3 with Next.js and AWS SDK v3?](https://www.mtechzilla.com/blogs/how-to-upload-images-and-videos-to-amazon-s3-with-next-js-and-aws-sdk-v3)
- [[Part4] TypeScript, PostgreSQL, Next.js, Prisma & GraphQLでApp作成](https://zenn.dev/kanasugi/articles/3539f68455136d)

### Features Expectation in the future

- Add `drag and drop` with [react-dropzone](https://react-dropzone.js.org/) or [@mantime/dropzone](https://mantine.dev/others/dropzone/)

**Comment by haseakito** [comment]
### Memo

This can a good reference too.
- [Fullstack App With TypeScript, PostgreSQL, Next.js, Prisma & GraphQL: Image upload](https://prisma.io/blog/fullstack-nextjs-graphql-prisma-4-1k1kc83x3v)
- [AWS S3にNext.js(React)から画像をアップロードする](https://qiita.com/fuku_pg/items/08fdea167f7d5432cf4c)

**Comment by haseakito** [comment]
### Memo

When uploading large size videos, try to use multipart upload wherever possible.

- [aws official example](https://github.com/aws/aws-sdk-js-v3/blob/main/lib/lib-storage/README.md#aws-sdklib-storage)
- [ReactでS3へのマルチアップロードを実装する (動画サイト構築までの道③)](https://zenn.dev/jinwatanabe/articles/66c712e44661d9#s3-%E3%81%AE%E7%94%A8%E6%84%8F)

**Comment by haseakito** [comment]
### Memo

AWS sdk throws this error. Does it have something to do with new version of sdk being imcompatible with Nextjs or new Nextjs app folder does not work well with AWS sdk?

> Import trace for requested module:
./node_modules/aws-crt/dist/native/binding.js
./node_modules/aws-crt/dist/native/auth.js
./node_modules/aws-crt/dist/index.js
./node_modules/@aws-sdk/util-user-agent-node/dist-cjs/is-crt-available.js
./node_modules/@aws-sdk/util-user-agent-node/dist-cjs/index.js
./node_modules/@aws-sdk/client-s3/dist-cjs/runtimeConfig.js
./node_modules/@aws-sdk/client-s3/dist-cjs/S3Client.js
./node_modules/@aws-sdk/client-s3/dist-cjs/index.js
./components/FileUpload.tsx
./app/profile/posts/[postId]/components/ImageForm.tsx

**Comment by haseakito** [comment]
### Memo 

Decided to use [UploadThing](https://uploadthing.com/) over AWS S3. Still, hosting on AWS would be nice though.

**Comment by abhay-ramesh** [comment]
> ### Memo
> Decided to use [UploadThing](https://uploadthing.com/) over AWS S3. Still, hosting on AWS would be nice though.

Hello there,

I'd like to recommend trying out the **next-s3-uploader** package, which I created specifically for Next.js app directories. It simplifies the file upload process seamlessly.

You can explore the [documentation](https://next-s3-uploader.abhayramesh.com/) for comprehensive details. Should you encounter any challenges or have questions, don't hesitate to get in touch with me or open a GitHub issue [here](https://github.com/abhay-ramesh/next-s3-uploader/issues). I'm here to provide assistance and support.

**Comment by haseakito** [comment]
@abhay-ramesh Thanks for your reply. Since I'm working on a bunch of different projects, I'm going to look into your repository in one of the projects. You've made a huge contribution to the Nextjs and also AWS ecosystem for developers around the world. Thank you and keep on grinding bro!!
